# Project Part 1

In this four-part project, we will explore what features make a good cup of coffee using reviews gathered from the Coffee Quality Institute by Data Scientist James LeDoux.

**By the end of this activity, you will:**

*   Import the project data as a Pandas DataFrame.
*   Select a research question for the project.
*   Perform preliminary exploratory data analysis steps.
*   Correctly select select necessary features to answer your research question.
*   Export the revised version data to your Google Drive and local machine.
*   Accurately comment each code block; code without comments will not be graded!

**Acknowledgements**

Coffee Quality Database courtesy of [James LeDoux](https://github.com/jldbc/coffee-quality-database), the [Coffee Quality Institute](https://database.coffeeinstitute.org/), and [TidyTuesday](https://github.com/rfordatascience/tidytuesday/tree/master/data/2020/2020-07-07).

# Data Dictionary

|variable              |class     |description |
|:---------------------|:---------|:-----------|
|total_cup_points      |double    | Total rating/points (0 - 100 scale) |
|species               |character | Species of coffee bean (arabica or robusta) |
|owner                 |character | Owner of the farm |
|country_of_origin     |character | Where the bean came from |
|farm_name             |character | Name of the farm |
|lot_number            |character | Lot number of the beans tested |
|mill                  |character | Mill where the beans were processed |
|ico_number            |character | International Coffee Organization number |
|company               |character | Company name |
|altitude              |character | Altitude |
|region                |character | Region where bean came from |
|producer              |character | Producer of the roasted bean |
|number_of_bags        |double    | Number of bags tested |
|bag_weight            |character | Bag weight tested |
|in_country_partner    |character | Partner for the country |
|harvest_year          |character | When the beans were harvested (year) |
|grading_date          |character | When the beans were graded|
|owner_1               |character | Who owns the beans|
|variety               |character | Variety of the beans |
|processing_method     |character | Method for processing|
|aroma                 |double    | Aroma grade * |
|flavor                |double    | Flavor grade * |
|aftertaste            |double    | Aftertaste grade * |
|acidity               |double    | Acidity grade  * |
|body                  |double    | Body grade * |
|balance               |double    | Balance grade * |
|uniformity            |double    | Uniformity grade * |
|clean_cup             |double    | Clean cup grade * |
|sweetness             |double    | Sweetness grade * |
|cupper_points         |double    | Cupper Points|
|moisture              |double    | Moisture Grade * |
|category_one_defects  |double    | Category one defects (count) * |
|quakers               |double    | quakers|
|color                 |character | Color of bean |
|category_two_defects  |double    |Category two defects (count) * |
|expiration            |character | Expiration date of the beans |
|certification_body    |character | Who certified it |
|certification_address |character | Certification body address |
|certification_contact |character | Certification contact |
|unit_of_measurement   |character | Unit of measurement |
|altitude_low_meters   |double    | Altitude low meters|
|altitude_high_meters  |double    | Altitude high meters |
|altitude_mean_meters  |double    | Altitude mean meters |

\* denotes **Quality Measures**

Note full description/examples at: [Coffee Quality Institute](https://database.coffeeinstitute.org/coffee/357789/grade).

## Task 1:  Setup Workspace

Download the project data by running the code block below.

In [2]:
!gdown 1dtO6gDyPemdP4TABdx-q7VVNw4gxKCDX

Downloading...
From: https://drive.google.com/uc?id=1dtO6gDyPemdP4TABdx-q7VVNw4gxKCDX
To: /content/coffee_ratings.csv
100% 604k/604k [00:00<00:00, 59.6MB/s]

Import nessary libraries and load data into a DataFrame.

In [3]:
#importing libraries
import gdown 
import pandas as pd
import numpy as np
#loading into a dataframe
Coffee = pd.read_csv('/content/coffee_ratings.csv')

Return the first few rows of the DataFrame to ensure the data has loaded correctly.

In [4]:
Coffee.head()

,total_cup_points,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,90.58,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,89.92,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,89.75,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,89.00,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,88.83,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

## Task 2: Select a research question

Select a research question of interest from the list below or enter your own in the text box below.

**Questions:**

1. Can we predict a coffee's rating using just its **Quality Measures**?
2. Are there significant differences in coffees grown at different altitudes and/or different counties?

**Note:**

- We will not be modeling in this part of the project.
- You may change your research question at a later date though it is recommended to stick with the same one throughout.

<br>

---

2. Are there significant differences in coffees grown at different altitudes and/or different counties?

---

## Task 3: Explore the data

Use techniques learned in previous activies to perform preliminary exploratory data analysis steps. In the next part of the project, we will take this further by creating data visualizations. You do not need to create visuals at this point of the project.

**Things to do:**

- Look for null or missing values with `isna()` and `sum()`.
- Find duplicate rows with `duplicated()`.
- Use `info()`, `describe()`, `value_counts()`, and `unique()` in a meaningful way.
- Crosstabulate `country_of_origin` with `species`. 

**Optional:**

- Discover outliers.

In [5]:
Coffee.isna() #noticing many missing in the lot_number and ico_number columns
#Coffee.sum() doesn't appear to be giving us as meaningful results in this case since there are many character values/ columns

,total_cup_points,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,True,True,True,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,True,True,True
1335,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1336,False,False,False,False,False,True,False,True,False,False,...,True,False,False,False,False,False,False,False,False,False
1337,False,False,False,False,True,True,True,False,False,True,...,False,False,False,False,False,False,False,True,True,True
1338,False,False,False,False,True,True,True,True,False,True,...,False,False,False,False,False,False,False,True,True,True

In [6]:
Coffee.duplicated() #it doesn't appear that we have any duplicates, which is good

0       False
1       False
2       False
3       False
4       False
        ...
1334    False
1335    False
1336    False
1337    False
1338    False
Length: 1339, dtype: bool

In [7]:
Coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   total_cup_points       1339 non-null   float64
 1   species                1339 non-null   object
 2   owner                  1332 non-null   object
 3   country_of_origin      1338 non-null   object
 4   farm_name              980 non-null    object
 5   lot_number             276 non-null    object
 6   mill                   1021 non-null   object
 7   ico_number             1182 non-null   object
 8   company                1130 non-null   object
 9   altitude               1113 non-null   object
 10  region                 1280 non-null   object
 11  producer               1107 non-null   object
 12  number_of_bags         1339 non-null   int64
 13  bag_weight             1339 non-null   object
 14  in_country_partner     1339 non-null   object
 15  harvest_year           1292 non-null   object
 16  grading_date           1339 non-null   object
 17  owner_1                1332 non-null   object
 18  variety                1113 non-null   object
 19  processing_method      1169 non-null   object
 20  aroma                  1339 non-null   float64
 21  flavor                 1339 non-null   float64
 22  aftertaste             1339 non-null   float64
 23  acidity                1339 non-null   float64
 24  body                   1339 non-null   float64
 25  balance                1339 non-null   float64
 26  uniformity             1339 non-null   float64
 27  clean_cup              1339 non-null   float64
 28  sweetness              1339 non-null   float64
 29  cupper_points          1339 non-null   float64
 30  moisture               1339 non-null   float64
 31  category_one_defects   1339 non-null   int64
 32  quakers                1338 non-null   float64
 33  color                  1121 non-null   object
 34  category_two_defects   1339 non-null   int64
 35  expiration             1339 non-null   object
 36  certification_body     1339 non-null   object
 37  certification_address  1339 non-null   object
 38  certification_contact  1339 non-null   object
 39  unit_of_measurement    1339 non-null   object
 40  altitude_low_meters    1109 non-null   float64
 41  altitude_high_meters   1109 non-null   float64
 42  altitude_mean_meters   1109 non-null   float64
dtypes: float64(16), int64(3), object(24)
memory usage: 449.9+ KB

The above seems like a much more helpful way to find missing values than the first approach, by looking at the non-null count column. Here we can see that there are a lot of missing values from the lot_number (because the non-null value is so low) and from farm_name. Moving forward, we probably wouldn't want to rely on these two variables too heavily. It also gives us useful information about the data types for each column.

In [8]:
Coffee.describe() #this is helpful for our numeric values

,total_cup_points,number_of_bags,aroma,flavor,aftertaste,acidity,body,balance,uniformity,clean_cup,sweetness,cupper_points,moisture,category_one_defects,quakers,category_two_defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
count,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1338.000000,1339.000000,1109.000000,1109.000000,1109.000000
mean,82.089851,154.182972,7.566706,7.520426,7.401083,7.535706,7.517498,7.518013,9.834877,9.835108,9.856692,7.503376,0.088379,0.479462,0.173393,3.556385,1750.713315,1799.347775,1775.030545
std,3.500575,129.987162,0.377560,0.398442,0.404463,0.379827,0.370064,0.408943,0.554591,0.763946,0.616102,0.473464,0.048287,2.549683,0.832121,5.312541,8669.440545,8668.805771,8668.626080
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,81.080000,14.000000,7.420000,7.330000,7.250000,7.330000,7.330000,7.330000,10.000000,10.000000,10.000000,7.250000,0.090000,0.000000,0.000000,0.000000,1100.000000,1100.000000,1100.000000
50%,82.500000,175.000000,7.580000,7.580000,7.420000,7.580000,7.500000,7.500000,10.000000,10.000000,10.000000,7.500000,0.110000,0.000000,0.000000,2.000000,1310.640000,1350.000000,1310.640000
75%,83.670000,275.000000,7.750000,7.750000,7.580000,7.750000,7.670000,7.750000,10.000000,10.000000,10.000000,7.750000,0.120000,0.000000,0.000000,4.000000,1600.000000,1650.000000,1600.000000
max,90.580000,1062.000000,8.750000,8.830000,8.670000,8.750000,8.580000,8.750000,10.000000,10.000000,10.000000,10.000000,0.280000,63.000000,11.000000,55.000000,190164.000000,190164.000000,190164.000000

In [9]:
Coffee.value_counts() #this output is a little overwhelming in its base form. At the moment, it does not seem too helpful

total_cup_points  species  owner                       country_of_origin  farm_name                 lot_number                         mill                             ico_number                  company                   altitude  region                                 producer                   number_of_bags  bag_weight  in_country_partner                          harvest_year  grading_date         owner_1                     variety     processing_method       aroma  flavor  aftertaste  acidity  body  balance  uniformity  clean_cup  sweetness  cupper_points  moisture  category_one_defects  quakers  color         category_two_defects  expiration           certification_body                          certification_address                     certification_contact                     unit_of_measurement  altitude_low_meters  altitude_high_meters  altitude_mean_meters
63.08             Arabica  exportadora atlantic, s.a.  Nicaragua          finca las marías          017-053-0211/ 017-053-0212         beneficio atlantic condega       017-053-0211/ 017-053-0212  exportadora atlantic s.a  1100      jalapa                                 Teófilo Narváez            550             69 kg       Instituto Hondureño del Café                2016          June 6th, 2017       Exportadora Atlantic, S.A.  Caturra     Other                   7.25   6.58    6.33        6.25     6.42  6.08     6.0         6.0        6.0        6.17           0.13      1                     0.0      Green         5                     June 6th, 2018       Instituto Hondureño del Café                b4660a57e9f8cc613ae5b8f02bfce8634c763ab4  7f521ca403540f81ec99daec7da19c2788393880  m                    1100.0000            1100.0000             1100.0000               1
83.00             Arabica  ipanema coffees             Brazil             fazenda capoeirnha        020/17                             dry mill                         002/1660/0080               ipanema coffees           890       south of minas                         Ipanema Agricola S.A       320             60 kg       Brazil Specialty Coffee Association         2017 / 2018   October 20th, 2017   Ipanema Coffees             Bourbon     Natural / Dry           7.58   7.50    7.50        7.75     7.67  7.50     10.0        10.0       10.0       7.50           0.00      0                     0.0      Green         4                     October 20th, 2018   Brazil Specialty Coffee Association         3297cfa4c538e3dd03f72cc4082c54f7999e1f9d  8900f0bf1d0b2bafe6807a73562c7677d57eb980  m                    890.0000             890.0000              890.0000                1
83.50             Arabica  juan luis alvarado romero   Guatemala          la esperanza              11/23/0145                         beneficio ixchel                 11/23/0145                  unex guatemala, s.a.      4000      oriente                                MARGARITA AVILA DE NUYENS  250             69 kg       Asociacion Nacional Del Café                2016          March 16th, 2016     Juan Luis Alvarado Romero   Bourbon     Washed / Wet            7.67   7.75    7.50        7.83     7.58  7.58     10.0        10.0       10.0       7.58           0.10      0                     2.0      Bluish-Green  5                     March 16th, 2017     Asociacion Nacional Del Café                b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53  724f04ad10ed31dbb9d260f0dfd221ba48be8a95  ft                   1219.2000            1219.2000             1219.2000               1
83.42             Arabica  juan luis alvarado romero   Guatemala          piamonte                  11/23/0696                         beneficio ixchel                 11/23/0696                  unex guatemala, s.a.      1700      san marcos                             JORGE LEAL                 50              69 kg       Asociacion Nacional Del Café                2017          August 23rd, 2017    Juan Luis Alvarado Romero   Bourbon     Washed / Wet            7.67   7.75    7.50        7.58     7.58  7.67     10.0        10.0       10.0       7.67           0.10      0                     0.0      Green         3                     August 23rd, 2018    Asociacion Nacional Del Café                b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53  724f04ad10ed31dbb9d260f0dfd221ba48be8a95  m                    1700.0000            1700.0000             1700.0000               1
                           ceca, s.a.                  Costa Rica         gamboa                    8885                               beneficio montañas del diamante  5-025-0032                  ceca,s.a.                 1850      tarrazu                                Martin Gutierrez           275             69 kg       Specialty Coffee Association of Costa Rica  2016          February 17th, 2017  CECA, S.A.                  Caturra     Washed / Wet            7.58   7.50    7.42        7.92     7.50  7.67     10.0        10.0       10.0       7.83           0.09      0                     0.0      Blue-Green    4                     February 17th, 2018  Specialty Coffee Association of Costa Rica  8e0b118f3cf3121ab27c5387deacdb7d4d2a60b1  5eb2b7129d9714c43825e44dc3bca9423de209e9  m                    1850.0000            1850.0000             1850.0000               1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
81.92             Arabica  bismarck castro             Honduras           los hicaques              63                                 cigrah s.a de c.v.               13-111-022                  cigrah s.a de c.v         1400      comayagua                              Reinerio Zepeda            274             67 kg       Instituto Hondureño del Café                2017          June 1st, 2017       Bismarck Castro             Caturra     Washed / Wet            7.58   7.50    7.25        7.33     7.42  7.50     10.0        10.0       10.0       7.33           0.12      0                     0.0      Green         1                     June 1st, 2018       Instituto Hondureño del Café                b4660a57e9f8cc613ae5b8f02bfce8634c763ab4  7f521ca403540f81ec99daec7da19c2788393880  m                    1400.0000            1400.0000             1400.0000               1
81.83             Arabica  juan luis alvarado romero   Guatemala          la esmeralda              11/23/0634                         beneficio ixchel                 11/23/0634                  unex guatemala, s.a.      518       oriente                                JESUS RAMIREZ              25              69 kg       Asociacion Nacional Del Café                2017          August 22nd, 2017    Juan Luis Alvarado Romero   Bourbon     Washed / Wet            7.42   7.50    7.25        7.50     7.33  7.42     10.0        10.0       10.0       7.42           0.10      1                     0.0      Green         1                     August 22nd, 2018    Asociacion Nacional Del Café                b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53  724f04ad10ed31dbb9d260f0dfd221ba48be8a95  ft                   157.8864             157.8864              157.8864                1
                                                                          chapultepec               11/23/0507                         beneficio ixchel                 11/23/0507                  unex guatemala, s.a.      3280      norte                                  CHAPULTEPEC                130             69 kg       Asociacion Nacional Del Café                2015          August 2nd, 2016     Juan Luis Alvarado Romero   Bourbon     Washed / Wet            7.58   7.50    7.33        7.42     7.58  7.25     10.0        10.0       10.0       7.17           0.10      2                     0.0      Green         6                     August 2nd, 2017     Asociacion Nacional Del Café                b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53  724f04ad10ed31dbb9d260f0dfd221ba48be8a95  m                    3280.0000            3280.0000             3280.0000               1
                           gabriel barbara             Brazil             helena                    2017/001                           copag                            02/0143-0/0292              volcafe ltda.             973       monte carmelo                          Helena Pingnatti Ricci     200             59 kg       Brazil Specialty Coffee Association         2016          January 20th, 2017   Gabriel Barbara             Mundo Novo  Natural / Dry           7.42   7.50    7.42        7.50     7.42  7.25     10.0        10.0       10.0       7.33           0.11      0                     1.0      Green         3                     January 20th, 2018   Brazil Specialty Coffee Association         3297cfa4c538e3dd03f72cc4082c54f7999e1f9d  8900f0bf1d0b2bafe6807a73562c7677d57eb980  m                    973.0000             973.0000              973.0000                1
86.58             Arabica  lin, che-hao krude 林哲豪      Taiwan             tsoustructive garden 鄒築園  Tsoustructive 2015 Sumatra Typica  tsoustructive garden 鄒築園         Taiwan                      taiwan coffee laboratory  1200      leye, alishan township, chiayi county  FANG,ZHENG-LUN 方政倫         20              50 kg       Specialty Coffee Association                2015          May 18th, 2016       Lin, Che-Hao Krude 林哲豪      Sumatra     Pulped natural / honey  8.00   8.00    8.00        8.25     8.00  8.17     10.0        10.0       10.0       8.17           0.00      0                     0.0      Green         0                     May 18th, 2017       Specialty Coffee Association                36d0d00a3724338ba7937c52a378d085f2172daa  0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660  m                    1200.0000            1200.0000             1200.0000               1
Length: 132, dtype: int64

In [10]:
Coffee['aroma'].unique()

array([8.67, 8.75, 8.42, 8.17, 8.25, 8.58, 8.08, 8.33, 8.  , 8.5 , 7.83,
       7.92, 7.67, 7.75, 7.58, 7.5 , 7.42, 7.81, 7.33, 7.25, 7.17, 7.08,
       5.08, 7.  , 6.92, 6.83, 6.75, 6.67, 6.42, 6.17, 6.5 , 6.33, 0.  ])

In [12]:
Coffee['country_of_origin'].unique() #since we're looking at potential altitude/ country differences, this could be important

array(['Ethiopia', 'Guatemala', 'Brazil', 'Peru', 'United States',
       'United States (Hawaii)', 'Indonesia', 'China', 'Costa Rica',
       'Mexico', 'Uganda', 'Honduras', 'Taiwan', 'Nicaragua',
       'Tanzania, United Republic Of', 'Kenya', 'Thailand', 'Colombia',
       'Panama', 'Papua New Guinea', 'El Salvador', 'Japan', 'Ecuador',
       'United States (Puerto Rico)', 'Haiti', 'Burundi', 'Vietnam',
       'Philippines', 'Rwanda', 'Malawi', 'Laos', 'Zambia', 'Myanmar',
       'Mauritius', 'Cote d?Ivoire', nan, 'India'], dtype=object)

In [14]:
Coffee['altitude'].unique() #there's a huge variety here

array(['1950-2200', '1600 - 1800 m', '1800-2200', nan, '1570-1700',
       '1795-1850', '1855-1955', 'meters above sea level: 1.872',
       'meters above sea level: 1.943', '2000 ft',
       'meters above sea level: 2.080', '1200-1800m', '1450',
       '1700-2000m', 'meters above sea level: 2.019', '1300 msnm', '1320',
       'meters above sea level: 2.112', '1250m', '1950', '1400', '1200',
       '1300', '1750-1800', '1800', 'meters above sea level: 1.941',
       '1.2', '1000 m', '1754', '900-1500m', '1520m-2200m', '1400-1900m',
       '1500-2000 m', '1400ft', '1400-1900', '1800 msnm', '1600',
       '1800-2000', '5000', '4650', '1700 mts', '1500 meters',
       '1300~1400 m.s.l', '1680', '1900m', '5600-5760 metros', '1400 m',
       '1700', '1770', 'above 1600 m', 'above 1200 m', '1550 msnm',
       '1550', '1250-1400 meter', '1400 msm', '2.560 msnm', '2136 msnm',
       '1900', '-1', '1580', '1100m', '1400 masl', '3500-5200 feet',
       'de 1600 a 1950 msnm', '800 m', '1620m', '1200m', '350',
       '1450 msnm', '1200 mts', '800-1050m', '1350', '170', '1150',
       '1750', '1750m', '2000', '4300', '1700-1850m', '1500', '5000 ft.',
       '4000 psn', '1600 a 1900 msnm', '1750 msnm', '1450 ~ 1700 m',
       '1300m', 'above 1100m', '2000 m', 'mmm', 'test', '900', '442 msnm',
       '1200m to 1350m', '900-1200m', '3600-6200 ft', '4400-4700 ft',
       '1000', '2560', '3607', '4000 psnm', '1170', '1700m', '3664',
       '1565', '3280', 'de 900 a 1100 msnm', '1850', '1545-1668 masl',
       '1530', "approx. 1'500 metres a.s.l.", '894m - 1183m',
       '1500-1700m', '442', '968', '1480', '1800m', '5440 - 5760 metros',
       '1550 m', '1260', '1700 msnm', '1650', '890', '934', '950公尺',
       '2527', '1', '480-570m', '1650-1703', '1200-1400',
       '800 meters above sea level', '1218', '1.250 m', '4921ft', '750',
       '2800 ft', '1500-1600', '700', '1300 mts', '1600 m.s.n.m',
       '1600 msnm', '1250', '800++', '1550-1700m', '4451 metros',
       '1800 - 2000', '1100', '1200-1600masl', '3702',
       'de 1.600 a 1.950 msnm', '1799', '4000', '1400m',
       '1600 on average', '1850 msnm', '1400 mts', '940', '4600 ft.',
       '439', '1330', '1813', '1500 msnm', '900-1200mtr', '1227',
       '1650 msnm', '1100-1300', '4200 feet', '1000 msnm', '1880', '2100',
       '1261', '800公尺', '1483', '175', '1600-1800msnm', '1880 msnm',
       '1800 m.s.n.m', '1901', '16.8', '1500msnm', '1400-1900 psn',
       "approx.1'500 metres a.s.l.", '1653', '1450 msnn', '5000 pies',
       '532', '1089', '1380', '1000m', '950m', '900m', '1850 m', '905',
       '700-800m', '1300 m', 'de 1.600 a 1.950 msn', '1300-1400m', '894',
       '872', '1473', '1645', '1300 a 1800 metros sobre el nivel del mar',
       '4500 pies', '900-1100', '1600 - 1950 msnm', '1500-1750 msnm',
       '4500', '1050 - 1850 msnm', '775', '1200 masl',
       '1600 + meters above sea level', '1059', '1300 meters',
       '11000 metros', '5440-5760 metros', '1248', '1040m', '1040',
       '4000psn', '1200-2000m', '1200 m', '1800 mts',
       '1400 meter above sea level', '518', '650', '1442 m', '1.65',
       '1400 thru 1850', '1200公尺', '1296', '1400- 1900', '1240 m', '950',
       '1800 meters (5900', '1050', '200 m', '1200-1300m dpl',
       '1400-1500 m', '1317', '900-1050m', '1679', '2285', 'huanuco',
       '1560', '1750 m.s.n.m', '1396', '982', '1268', '5500 metros',
       '1450 m', '600 m', '5500-6000 psnm', '441', '1200 a 1400', '1180m',
       '650 m', '1338', '533', '4563', '1500-1800', '1200-1600m', '1144',
       '1200-1400 masl', '1500 - 1700', '1.3', '944', '1300- 1400',
       '2500m', '600m', '1400 m.s.n.m.', '600-700 m', '1050m', '1020',
       '1300 a 1800 mtrs. a nivel del mar', '1877', '1000-1500m', '981',
       '690', '973', '4001', '1350-1500', '1400 msnm', '700m', '1556m',
       '1550 meters', 'de 1.600 a 1950 msnm', '900-950m',
       '1600-1800 msnm', '774', '150 m', '750 m', '190164', '800',
       '850 m', '4500-6000 feet', '160-200m', '4000 ft', '1200 msm',
       '1599m', '900 m', '400-1250m', '1.25', '1050 - 1850', '110公尺',
       '1422', '1550 mts.', '1550 meter', '763', '1130', '680',
       '1400 msn', '5000 f', '100/2000', '1450 mals', '990-1000m', '0',
       '695', '1100 m.o.s.l.', '5600 feet', '1456', '1500 mts', '1642',
       '758m', '1350 snn', '1525 m', '1100 m', '200', '3500 ft', '550公尺',
       'between 700 and 1400 meters', '688 m', '300 m', '1186', '1210',
       '100', '3825', '1100.00 mosl', '1450 masl', '1680m',
       '~1000 meters', '1200-1500', '1.85', '4540 metros', '50', '280',
       '1250 m', '3800', '4000 p.s.n.m.', '6100 metros', '600公尺', '1450m',
       '995', '3000 ft', '4287', '900 m.s.n.m.', '700 m', '808',
       '1100 - 1275 mts', '850公尺', '250 m', '3845', '1300 to 1500 meters',
       '1901.64', '800-1200', '500-700m', '1022', '975', '1264',
       '3500 - 5200 feet', '700m公尺', '850', '12oo', '800m', '1600 meters',
       '4000 p.s.n.m', '1200 meters', '750-800 m', '900-1500 masl',
       '3500', '1000+ meters', '1280', '1140', '640m-1400m',
       '1000 meters', '~350m', '1488', '3170', '1212', '1200-1300',
       "3000'", '750m', '3140', '900-1300', '1095', '1367', '1745', '40',
       '795 meters'], dtype=object)

In [16]:
pd.crosstab(Coffee['country_of_origin'],Coffee['species'], dropna=False) #236 Arabica in Mexico!

species                       Arabica  Robusta
country_of_origin
Brazil                            132        0
Burundi                             2        0
China                              16        0
Colombia                          183        0
Costa Rica                         51        0
Cote d?Ivoire                       1        0
Ecuador                             1        2
El Salvador                        21        0
Ethiopia                           44        0
Guatemala                         181        0
Haiti                               6        0
Honduras                           53        0
India                               1       13
Indonesia                          20        0
Japan                               1        0
Kenya                              25        0
Laos                                3        0
Malawi                             11        0
Mauritius                           1        0
Mexico                            236        0
Myanmar                             8        0
Nicaragua                          26        0
Panama                              4        0
Papua New Guinea                    1        0
Peru                               10        0
Philippines                         5        0
Rwanda                              1        0
Taiwan                             75        0
Tanzania, United Republic Of       40        0
Thailand                           32        0
Uganda                             26       10
United States                       8        2
United States (Hawaii)             73        0
United States (Puerto Rico)         4        0
Vietnam                             7        1
Zambia                              1        0

## Task 4: Subset Data

We won't be needing every column in the dataset to perform our analysis. Subset the DataFrame by selecting only the features relevant to your research question. All other columns should be dropped.

*Hint: It may be easier to select the columns you need rather than drop the columns you don't ([Reference](https://www.geeksforgeeks.org/how-to-select-multiple-columns-in-a-pandas-dataframe/)).*

In [20]:
Coffee_sub = Coffee[['species','country_of_origin','altitude','region','number_of_bags','bag_weight','variety','aroma','flavor','aftertaste','acidity','body','balance','uniformity','clean_cup','sweetness','cupper_points','moisture','category_one_defects','color','category_two_defects','altitude_low_meters','altitude_high_meters','altitude_mean_meters']]

In the above, there are many obvious columns included but I'll explain some of the rationale for the less obvious ones. number_of_bags, bag_weight, and variety I felt should be included to make sure that our measure of "differences" be properly represented by a similar amount of reports from each area, so there isn't one region that is over represented.

## Task 5: Export Data

Export the revised version of the DataFrame to your Google Drive.

In [21]:
Coffee_sub.to_csv('NewCoffee')

Download the revised version of the DataFrame to your local machine.

In [22]:
from google.colab import files
files.download('NewCoffee')

## Task 6: Thought Question

> *A common issue in statistical analysis is the concept of 'fishing' for significant results. In other words, a researcher explores many different models to find something statistically significant.<br><br>Good research starts with an initial question based on a domain expert's knowledge of the field, identifies (or collects data), and then pursues only the variables specified in the original question in the model.<br><br>By 'wrangling,' you avoid the temptation to 'fish' your data. Consider a scenario where a researcher does 'fish' for statistical results. What might be an ethical issue with such an action?*

Fishing for results fundamentally destroys the integrity of the reseach. It is akin to trying to search for an answer to your question on Google and ignoring reputably-sourced responses in favor of an unfiltered blog post that confirms because it your bias. By fishing for results, you have already made up your mind for how you assume the answer should look that you ignore the truth of the data in favor of your assumption. You may consciously or unconsciously tamper with the analysis results in order to confirm your anticipated narative, effectively making your analysis void.